CREATE DATABASE QLKHO
GO
use QLKHO
CREATE TABLE TON(
	MAVT  NCHAR(20) NOT NULL PRIMARY KEY,
	TENVT NCHAR(20),
	SOLUONGT INT
	)
CREATE TABLE NHAP(
	SOHDN NCHAR(20) NOT NULL,
	MAVT NCHAR(20) NOT NULL,
	SOLUONGN INT,
	DONGIAN MONEY,
	NGAYN DATE,
	CONSTRAINT PK_SOHDN_MAVT PRIMARY KEY (SOHDN, MAVT),
	CONSTRAINT FK_MAVT FOREIGN KEY (MAVT) REFERENCES TON(MAVT) ON UPDATE CASCADE ON DELETE CASCADE)
CREATE TABLE XUAT(
	SOHDX NCHAR(20) NOT NULL,
	MAVT NCHAR(20) NOT NULL,
	SOLUONGX INT,
	DONGIAX MONEY,
	NGAYX DATE,
	CONSTRAINT PK_SOHDX_MAVT PRIMARY KEY (SOHDX, MAVT),
	CONSTRAINT FK_MAVTX FOREIGN KEY (MAVT) REFERENCES TON(MAVT) ON UPDATE CASCADE ON DELETE CASCADE)
INSERT INTO TON (MAVT, TENVT, SOLUONGT)
VALUES
    ('VT01', 'Vat Tu 1', 100),
    ('VT02', 'Vat Tư 2', 150),
    ('VT03', 'Vat Tư 3', 200),
    ('VT04', 'Vat Tư 4', 120),
    ('VT05', 'Vat Tư 5', 80);
INSERT INTO NHAP (SOHDN, MAVT, SOLUONGN, DONGIAN, NGAYN)
VALUES
    ('HDN01', 'VT01', 50, 10.5, '2023-01-10'),
    ('HDN02', 'VT02', 30, 8.75, '2023-02-15'),
    ('HDN03', 'VT03', 40, 12.0, '2023-03-20'),
	('HDN04', 'VT02', 30, 8.75, '2023-02-15'),
    ('HDN05', 'VT03', 40, 12.0, '2023-03-20');
INSERT INTO XUAT (SOHDX, MAVT, SOLUONGX, DONGIAX, NGAYX)
VALUES
	 ('HDX03', 'VT03', 20, 15.0, '2023-03-05'),
    ('HDX01', 'VT04', 20, 15.0, '2023-02-05'),
    ('HDX02', 'VT05', 15, 18.5, '2023-03-10'),
	('HDX06', 'VT05', 150, 18.5, '2023-03-10');
	--
SELECT * FROM TON
--
SELECT TON.MAVT,TENVT, SUM(XUAT.SOLUONGX * XUAT.DONGIAX) AS TIENBAN
FROM TON INNER JOIN XUAT ON TON.MAVT =XUAT.MAVT
GROUP BY TON.MAVT,TENVT;
--Thống kê số lượng XUẤT theo tên vật tư

SELECT TON.TENVT, SUM(SOLUONGX) AS SOLUONGXUAT
FROM TON JOIN XUAT ON TON.MAVT=XUAT.MAVT
GROUP BY TENVT;
--Thống kê số lượng NHẬP theo tên vật tư
SELECT TON.TENVT, SUM(SOLUONGN) AS SOLUONGNHAP
FROM TON JOIN NHAP ON TON.MAVT=NHAP.MAVT
GROUP BY TENVT;
--DUA RA TONG SO LUONG CON TRONG KHO
SELECT TON.MAVT,TENVT,SUM(SOLUONGN)-SUM(SOLUONGX)+SUM(SOLUONGT) AS SOLUONGCON
FROM TON 
LEFT JOIN NHAP ON TON.MAVT=NHAP.MAVT
LEFT JOIN XUAT ON TON.MAVT=XUAT.MAVT
GROUP BY TENVT,TON.MAVT
--

--chỉnh giá trị null bằng 0
SELECT TON.MAVT, TON.TENVT, 
       ISNULL(SUM(NHAP.SOLUONGN), 0) AS TongNhap, 
       ISNULL(SUM(XUAT.SOLUONGX), 0) AS TongXuat,
       TON.SOLUONGT AS TonKho,
       ISNULL(SUM(NHAP.SOLUONGN), 0) - ISNULL(SUM(XUAT.SOLUONGX), 0) + TON.SOLUONGT AS SoLuongCon
FROM TON
LEFT JOIN NHAP ON TON.MAVT = NHAP.MAVT
LEFT JOIN XUAT ON TON.MAVT = XUAT.MAVT
GROUP BY TON.MAVT, TON.TENVT, TON.SOLUONGT;

--DUA RA TEN VAT TU SO LUONG TON NHIEU NHAT
SELECT TON.TENVT, MAVT
FROM TON
WHERE SOLUONGT=(select MAX(SOLUONGT)from TON )

--ĐƯA RA CÁC VẬT TƯ CÓ TỔNG SỐ LƯỢNG XUẤT LỚN HƠN 100
SELECT TON.MAVT, TENVT 
FROM TON JOIN XUAT ON TON.MAVT=XUAT.MAVT
GROUP BY TON.MAVT, TENVT
HAVING SUM(SOLUONGX)> 100;
--THANG NAM XUAT, TONG SO LUONG X
SELECT  MONTH(NGAYX) THANGXUAT,YEAR(NGAYX) NAMXUAT,SUM(SOLUONGX)
FROM XUAT
GROUP BY  MONTH(NGAYX),YEAR(NGAYX)
--. Đưa ra mã vật tư. tên vật tư. số lượng nhập. số lượng xuất. đơn giá N. đơn giá X. ngày nhập. Ngày xuất
SELECT TON.MAVT, TENVT, ISNULL(SUM(SOLUONGN),0),  ISNULL(SUM(SOLUONGX),0), DONGIAN,DONGIAX, NGAYN,NGAYX
FROM TON 
JOIN NHAP ON TON.MAVT=NHAP.MAVT
JOIN XUAT ON TON.MAVT=XUAT.MAVT
GROUP BY TON.MAVT, TENVT, NGAYN, NGAYX,DONGIAN,DONGIAX

SELECT
    TON.MaVT,
    TON.TenVT,
    COALESCE(SUM(NHAP.SoLuongN), 0) AS SoLuongNhap,
    COALESCE(SUM(XUAT.SoLuongX), 0) AS SoLuongXuat,
    COALESCE(MAX(NHAP.DonGiaN), 0) AS DonGiaNhap,
    COALESCE(MAX(XUAT.DonGiaX), 0) AS DonGiaXuat,
    NHAP.NgayN AS NgayNhap,
    XUAT.NgayX AS NgayXuat
FROM
    TON
LEFT JOIN
    NHAP ON TON.MaVT = NHAP.MaVT
LEFT JOIN
    XUAT ON TON.MaVT = XUAT.MaVT
GROUP BY
    TON.MaVT, TON.TenVT, NHAP.NgayN, XUAT.NgayX
ORDER BY
    TON.MaVT;


	--. Đưa ra mã vật tư. tên vật tư và tổng số lượng còn lại trong kho. biết còn lại = SoluongN-SoLuongX+SoLuongT 
	--theo từng loại Vật tư  trong năm 2015
	SELECT
    TON.MaVT,
    TON.TenVT,
    COALESCE(SUM(NHAP.SoLuongN), 0) - COALESCE(SUM(XUAT.SoLuongX), 0) + COALESCE(SUM(TON.SoLuongT), 0) AS SoLuongConLai
FROM
    TON
LEFT JOIN
    NHAP ON TON.MaVT = NHAP.MaVT AND YEAR(NHAP.NgayN) = 2015
LEFT JOIN
    XUAT ON TON.MaVT = XUAT.MaVT AND YEAR(XUAT.NgayX) = 2015

GROUP BY
    TON.MaVT, TON.TenVT


	--
SELECT TON.MAVT, TENVT,COALESCE(SUM(SOLUONGN),0)-COALESCE(SUM(SOLUONGX),0) + COALESCE(SUM(SOLUONGT),0) AS SOLUONGCON
FROM TON
LEFT JOIN NHAP ON TON.MAVT=NHAP.MAVT AND YEAR(NGAYN)=2015
LEFT JOIN XUAT ON TON.MAVT=XUAT.MAVT AND YEAR(NGAYX)=2015
GROUP BY TON.MAVT,TENVT
 --10.  Hiển thị danh sách vật tư chưa được xuất lần nào
 SELECT
    TON.MaVT,
    TON.TenVT
FROM
    TON
LEFT JOIN
    XUAT ON TON.MaVT = XUAT.MaVT
WHERE
    XUAT.MaVT IS NULL;
---
SELECT TON.MAVT, TENVT
FROM TON
WHERE TON.MAVT NOT IN (SELECT XUAT.MAVT FROM XUAT)
