USE master
IF(EXISTS( SELECT * FROM SYSDATABASES))
DROP DATABASE QLSACH
GO
CREATE DATABASE QLSACH
USE QLSACH
GO
CREATE TABLE SACH(
MASACH CHAR(10) PRIMARY KEY ,
TENSACH NVARCHAR(50) NOT NULL,
THELOAI NVARCHAR(50),
GIABAN MONEY NOT NULL)

CREATE TABLE HOADON(
MAHD CHAR(10) PRIMARY KEY,
NGAYLAP DATE,
GHICHU NVARCHAR(MAX))

CREATE TABLE CHITIETHOADON(
MASACH CHAR(10),
MAHD CHAR(10),
SOLUONG INT,
CONSTRAINT PK_SACH_HD PRIMARY KEY(MASACH,MAHD),
CONSTRAINT FK_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD) ON UPDATE CASCADE ON DELETE CASCADE)

INSERT INTO SACH VALUES
(N'1',N'ROBOT',N'VIENTUONG',20000),
(N'2',N'BLACK',N'VIENTUONG',30000),
(N'3',N'DORAMON',N'TRUYENTRANH',60000)

INSERT INTO HOADON VALUES
(N'HD1','2022-12-8','HAY'),
(N'HD2','2022-4-8','NOIBAT'),
(N'HD3','2021-2-8','NHIEU')

INSERT INTO CHITIETHOADON VALUES
(N'1',N'HD2',11),
(N'3',N'HD1',1),
(N'2',N'HD3',10)

SELECT * FROM SACH
SELECT * FROM HOADON
SELECT * FROM CHITIETHOADON

SELECT * FROM CHITIETHOADON
UPDATE CHITIETHOADON SET SOLUONG=SOLUONG+1
SELECT * FROM CHITIETHOADON

SELECT * FROM SACH
SELECT TENSACH,GIABAN FROM SACH
WHERE THELOAI LIKE 'V%'

SELECT * FROM HOADON
SELECT * FROM SACH
SELECT HOADON.MAHD,NGAYLAP
FROM HOADON
JOIN CHITIETHOADON ON HOADON.MAHD=CHITIETHOADON.MAHD
JOIN SACH ON SACH.MASACH=CHITIETHOADON.MASACH
WHERE THELOAI='VIENTUONG'


SELECT MAHD, SUM(SOLUONG) AS TONGSOLUONGSACH FROM CHITIETHOADON
GROUP BY MAHD

SELECT * FROM SACH
SELECT TENSACH  FROM SACH
WHERE GIABAN IN (SELECT MIN(GIABAN) FROM SACH)